/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedTeamsRouteImport } from './routes/_authenticated/teams'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedQueueRouteImport } from './routes/_authenticated/queue'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPrioritiesRouteImport } from './routes/_authenticated/priorities'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConversationsRouteImport } from './routes/_authenticated/conversations'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedChannelsRouteImport } from './routes/_authenticated/channels'
import { Route as AuthenticatedAutomationsRouteImport } from './routes/_authenticated/automations'
import { Route as AuthenticatedAiAssistantRouteImport } from './routes/_authenticated/ai-assistant'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicLeadsIndexRouteImport } from './routes/api/public/leads/index'
import { Route as ApiPublicConversationsIndexRouteImport } from './routes/api/public/conversations/index'
import { Route as ApiPublicContactsIndexRouteImport } from './routes/api/public/contacts/index'
import { Route as ApiPublicWebhooksUpsertConversationRouteImport } from './routes/api/public/webhooks/upsert-conversation'
import { Route as ApiPublicWebhooksUpdateTaskRouteImport } from './routes/api/public/webhooks/update-task'
import { Route as ApiPublicWebhooksUpdateLeadRouteImport } from './routes/api/public/webhooks/update-lead'
import { Route as ApiPublicWebhooksUpdateContactRouteImport } from './routes/api/public/webhooks/update-contact'
import { Route as ApiPublicWebhooksNewTaskRouteImport } from './routes/api/public/webhooks/new-task'
import { Route as ApiPublicWebhooksNewMessageRouteImport } from './routes/api/public/webhooks/new-message'
import { Route as ApiPublicWebhooksNewLeadRouteImport } from './routes/api/public/webhooks/new-lead'
import { Route as ApiPublicWebhooksNewContactRouteImport } from './routes/api/public/webhooks/new-contact'
import { Route as ApiPublicWebhooksChannelStatusRouteImport } from './routes/api/public/webhooks/channel-status'
import { Route as ApiPublicWebhooksAiAnalysisRouteImport } from './routes/api/public/webhooks/ai-analysis'
import { Route as ApiPublicLeadsIdStatusRouteImport } from './routes/api/public/leads/$id/status'
import { Route as ApiPublicLeadsIdNoteRouteImport } from './routes/api/public/leads/$id/note'
import { Route as ApiPublicConversationsIdMessagesRouteImport } from './routes/api/public/conversations/$id/messages'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamsRoute = AuthenticatedTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQueueRoute = AuthenticatedQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrioritiesRoute = AuthenticatedPrioritiesRouteImport.update({
  id: '/priorities',
  path: '/priorities',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConversationsRoute =
  AuthenticatedConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChannelsRoute = AuthenticatedChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomationsRoute =
  AuthenticatedAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiAssistantRoute =
  AuthenticatedAiAssistantRouteImport.update({
    id: '/ai-assistant',
    path: '/ai-assistant',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadsIndexRoute = ApiPublicLeadsIndexRouteImport.update({
  id: '/api/public/leads/',
  path: '/api/public/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConversationsIndexRoute =
  ApiPublicConversationsIndexRouteImport.update({
    id: '/api/public/conversations/',
    path: '/api/public/conversations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicContactsIndexRoute = ApiPublicContactsIndexRouteImport.update({
  id: '/api/public/contacts/',
  path: '/api/public/contacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksUpsertConversationRoute =
  ApiPublicWebhooksUpsertConversationRouteImport.update({
    id: '/api/public/webhooks/upsert-conversation',
    path: '/api/public/webhooks/upsert-conversation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksUpdateTaskRoute =
  ApiPublicWebhooksUpdateTaskRouteImport.update({
    id: '/api/public/webhooks/update-task',
    path: '/api/public/webhooks/update-task',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksUpdateLeadRoute =
  ApiPublicWebhooksUpdateLeadRouteImport.update({
    id: '/api/public/webhooks/update-lead',
    path: '/api/public/webhooks/update-lead',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksUpdateContactRoute =
  ApiPublicWebhooksUpdateContactRouteImport.update({
    id: '/api/public/webhooks/update-contact',
    path: '/api/public/webhooks/update-contact',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksNewTaskRoute =
  ApiPublicWebhooksNewTaskRouteImport.update({
    id: '/api/public/webhooks/new-task',
    path: '/api/public/webhooks/new-task',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksNewMessageRoute =
  ApiPublicWebhooksNewMessageRouteImport.update({
    id: '/api/public/webhooks/new-message',
    path: '/api/public/webhooks/new-message',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksNewLeadRoute =
  ApiPublicWebhooksNewLeadRouteImport.update({
    id: '/api/public/webhooks/new-lead',
    path: '/api/public/webhooks/new-lead',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksNewContactRoute =
  ApiPublicWebhooksNewContactRouteImport.update({
    id: '/api/public/webhooks/new-contact',
    path: '/api/public/webhooks/new-contact',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksChannelStatusRoute =
  ApiPublicWebhooksChannelStatusRouteImport.update({
    id: '/api/public/webhooks/channel-status',
    path: '/api/public/webhooks/channel-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksAiAnalysisRoute =
  ApiPublicWebhooksAiAnalysisRouteImport.update({
    id: '/api/public/webhooks/ai-analysis',
    path: '/api/public/webhooks/ai-analysis',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLeadsIdStatusRoute = ApiPublicLeadsIdStatusRouteImport.update({
  id: '/api/public/leads/$id/status',
  path: '/api/public/leads/$id/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadsIdNoteRoute = ApiPublicLeadsIdNoteRouteImport.update({
  id: '/api/public/leads/$id/note',
  path: '/api/public/leads/$id/note',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConversationsIdMessagesRoute =
  ApiPublicConversationsIdMessagesRouteImport.update({
    id: '/api/public/conversations/$id/messages',
    path: '/api/public/conversations/$id/messages',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/channels': typeof AuthenticatedChannelsRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/conversations': typeof AuthenticatedConversationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/priorities': typeof AuthenticatedPrioritiesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/teams': typeof AuthenticatedTeamsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/webhooks/ai-analysis': typeof ApiPublicWebhooksAiAnalysisRoute
  '/api/public/webhooks/channel-status': typeof ApiPublicWebhooksChannelStatusRoute
  '/api/public/webhooks/new-contact': typeof ApiPublicWebhooksNewContactRoute
  '/api/public/webhooks/new-lead': typeof ApiPublicWebhooksNewLeadRoute
  '/api/public/webhooks/new-message': typeof ApiPublicWebhooksNewMessageRoute
  '/api/public/webhooks/new-task': typeof ApiPublicWebhooksNewTaskRoute
  '/api/public/webhooks/update-contact': typeof ApiPublicWebhooksUpdateContactRoute
  '/api/public/webhooks/update-lead': typeof ApiPublicWebhooksUpdateLeadRoute
  '/api/public/webhooks/update-task': typeof ApiPublicWebhooksUpdateTaskRoute
  '/api/public/webhooks/upsert-conversation': typeof ApiPublicWebhooksUpsertConversationRoute
  '/api/public/contacts/': typeof ApiPublicContactsIndexRoute
  '/api/public/conversations/': typeof ApiPublicConversationsIndexRoute
  '/api/public/leads/': typeof ApiPublicLeadsIndexRoute
  '/api/public/conversations/$id/messages': typeof ApiPublicConversationsIdMessagesRoute
  '/api/public/leads/$id/note': typeof ApiPublicLeadsIdNoteRoute
  '/api/public/leads/$id/status': typeof ApiPublicLeadsIdStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/channels': typeof AuthenticatedChannelsRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/conversations': typeof AuthenticatedConversationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/priorities': typeof AuthenticatedPrioritiesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/teams': typeof AuthenticatedTeamsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/webhooks/ai-analysis': typeof ApiPublicWebhooksAiAnalysisRoute
  '/api/public/webhooks/channel-status': typeof ApiPublicWebhooksChannelStatusRoute
  '/api/public/webhooks/new-contact': typeof ApiPublicWebhooksNewContactRoute
  '/api/public/webhooks/new-lead': typeof ApiPublicWebhooksNewLeadRoute
  '/api/public/webhooks/new-message': typeof ApiPublicWebhooksNewMessageRoute
  '/api/public/webhooks/new-task': typeof ApiPublicWebhooksNewTaskRoute
  '/api/public/webhooks/update-contact': typeof ApiPublicWebhooksUpdateContactRoute
  '/api/public/webhooks/update-lead': typeof ApiPublicWebhooksUpdateLeadRoute
  '/api/public/webhooks/update-task': typeof ApiPublicWebhooksUpdateTaskRoute
  '/api/public/webhooks/upsert-conversation': typeof ApiPublicWebhooksUpsertConversationRoute
  '/api/public/contacts': typeof ApiPublicContactsIndexRoute
  '/api/public/conversations': typeof ApiPublicConversationsIndexRoute
  '/api/public/leads': typeof ApiPublicLeadsIndexRoute
  '/api/public/conversations/$id/messages': typeof ApiPublicConversationsIdMessagesRoute
  '/api/public/leads/$id/note': typeof ApiPublicLeadsIdNoteRoute
  '/api/public/leads/$id/status': typeof ApiPublicLeadsIdStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/_authenticated/automations': typeof AuthenticatedAutomationsRoute
  '/_authenticated/channels': typeof AuthenticatedChannelsRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/conversations': typeof AuthenticatedConversationsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/priorities': typeof AuthenticatedPrioritiesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/queue': typeof AuthenticatedQueueRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/teams': typeof AuthenticatedTeamsRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/webhooks/ai-analysis': typeof ApiPublicWebhooksAiAnalysisRoute
  '/api/public/webhooks/channel-status': typeof ApiPublicWebhooksChannelStatusRoute
  '/api/public/webhooks/new-contact': typeof ApiPublicWebhooksNewContactRoute
  '/api/public/webhooks/new-lead': typeof ApiPublicWebhooksNewLeadRoute
  '/api/public/webhooks/new-message': typeof ApiPublicWebhooksNewMessageRoute
  '/api/public/webhooks/new-task': typeof ApiPublicWebhooksNewTaskRoute
  '/api/public/webhooks/update-contact': typeof ApiPublicWebhooksUpdateContactRoute
  '/api/public/webhooks/update-lead': typeof ApiPublicWebhooksUpdateLeadRoute
  '/api/public/webhooks/update-task': typeof ApiPublicWebhooksUpdateTaskRoute
  '/api/public/webhooks/upsert-conversation': typeof ApiPublicWebhooksUpsertConversationRoute
  '/api/public/contacts/': typeof ApiPublicContactsIndexRoute
  '/api/public/conversations/': typeof ApiPublicConversationsIndexRoute
  '/api/public/leads/': typeof ApiPublicLeadsIndexRoute
  '/api/public/conversations/$id/messages': typeof ApiPublicConversationsIdMessagesRoute
  '/api/public/leads/$id/note': typeof ApiPublicLeadsIdNoteRoute
  '/api/public/leads/$id/status': typeof ApiPublicLeadsIdStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ai-assistant'
    | '/automations'
    | '/channels'
    | '/contacts'
    | '/conversations'
    | '/dashboard'
    | '/leads'
    | '/pipeline'
    | '/priorities'
    | '/profile'
    | '/queue'
    | '/settings'
    | '/support'
    | '/teams'
    | '/templates'
    | '/.lovable/oauth/consent'
    | '/api/public/webhooks/ai-analysis'
    | '/api/public/webhooks/channel-status'
    | '/api/public/webhooks/new-contact'
    | '/api/public/webhooks/new-lead'
    | '/api/public/webhooks/new-message'
    | '/api/public/webhooks/new-task'
    | '/api/public/webhooks/update-contact'
    | '/api/public/webhooks/update-lead'
    | '/api/public/webhooks/update-task'
    | '/api/public/webhooks/upsert-conversation'
    | '/api/public/contacts/'
    | '/api/public/conversations/'
    | '/api/public/leads/'
    | '/api/public/conversations/$id/messages'
    | '/api/public/leads/$id/note'
    | '/api/public/leads/$id/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ai-assistant'
    | '/automations'
    | '/channels'
    | '/contacts'
    | '/conversations'
    | '/dashboard'
    | '/leads'
    | '/pipeline'
    | '/priorities'
    | '/profile'
    | '/queue'
    | '/settings'
    | '/support'
    | '/teams'
    | '/templates'
    | '/.lovable/oauth/consent'
    | '/api/public/webhooks/ai-analysis'
    | '/api/public/webhooks/channel-status'
    | '/api/public/webhooks/new-contact'
    | '/api/public/webhooks/new-lead'
    | '/api/public/webhooks/new-message'
    | '/api/public/webhooks/new-task'
    | '/api/public/webhooks/update-contact'
    | '/api/public/webhooks/update-lead'
    | '/api/public/webhooks/update-task'
    | '/api/public/webhooks/upsert-conversation'
    | '/api/public/contacts'
    | '/api/public/conversations'
    | '/api/public/leads'
    | '/api/public/conversations/$id/messages'
    | '/api/public/leads/$id/note'
    | '/api/public/leads/$id/status'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ai-assistant'
    | '/_authenticated/automations'
    | '/_authenticated/channels'
    | '/_authenticated/contacts'
    | '/_authenticated/conversations'
    | '/_authenticated/dashboard'
    | '/_authenticated/leads'
    | '/_authenticated/pipeline'
    | '/_authenticated/priorities'
    | '/_authenticated/profile'
    | '/_authenticated/queue'
    | '/_authenticated/settings'
    | '/_authenticated/support'
    | '/_authenticated/teams'
    | '/_authenticated/templates'
    | '/.lovable/oauth/consent'
    | '/api/public/webhooks/ai-analysis'
    | '/api/public/webhooks/channel-status'
    | '/api/public/webhooks/new-contact'
    | '/api/public/webhooks/new-lead'
    | '/api/public/webhooks/new-message'
    | '/api/public/webhooks/new-task'
    | '/api/public/webhooks/update-contact'
    | '/api/public/webhooks/update-lead'
    | '/api/public/webhooks/update-task'
    | '/api/public/webhooks/upsert-conversation'
    | '/api/public/contacts/'
    | '/api/public/conversations/'
    | '/api/public/leads/'
    | '/api/public/conversations/$id/messages'
    | '/api/public/leads/$id/note'
    | '/api/public/leads/$id/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  ApiPublicWebhooksAiAnalysisRoute: typeof ApiPublicWebhooksAiAnalysisRoute
  ApiPublicWebhooksChannelStatusRoute: typeof ApiPublicWebhooksChannelStatusRoute
  ApiPublicWebhooksNewContactRoute: typeof ApiPublicWebhooksNewContactRoute
  ApiPublicWebhooksNewLeadRoute: typeof ApiPublicWebhooksNewLeadRoute
  ApiPublicWebhooksNewMessageRoute: typeof ApiPublicWebhooksNewMessageRoute
  ApiPublicWebhooksNewTaskRoute: typeof ApiPublicWebhooksNewTaskRoute
  ApiPublicWebhooksUpdateContactRoute: typeof ApiPublicWebhooksUpdateContactRoute
  ApiPublicWebhooksUpdateLeadRoute: typeof ApiPublicWebhooksUpdateLeadRoute
  ApiPublicWebhooksUpdateTaskRoute: typeof ApiPublicWebhooksUpdateTaskRoute
  ApiPublicWebhooksUpsertConversationRoute: typeof ApiPublicWebhooksUpsertConversationRoute
  ApiPublicContactsIndexRoute: typeof ApiPublicContactsIndexRoute
  ApiPublicConversationsIndexRoute: typeof ApiPublicConversationsIndexRoute
  ApiPublicLeadsIndexRoute: typeof ApiPublicLeadsIndexRoute
  ApiPublicConversationsIdMessagesRoute: typeof ApiPublicConversationsIdMessagesRoute
  ApiPublicLeadsIdNoteRoute: typeof ApiPublicLeadsIdNoteRoute
  ApiPublicLeadsIdStatusRoute: typeof ApiPublicLeadsIdStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teams': {
      id: '/_authenticated/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthenticatedTeamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/queue': {
      id: '/_authenticated/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof AuthenticatedQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/priorities': {
      id: '/_authenticated/priorities'
      path: '/priorities'
      fullPath: '/priorities'
      preLoaderRoute: typeof AuthenticatedPrioritiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversations': {
      id: '/_authenticated/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AuthenticatedConversationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/channels': {
      id: '/_authenticated/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AuthenticatedChannelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automations': {
      id: '/_authenticated/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AuthenticatedAutomationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-assistant': {
      id: '/_authenticated/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AuthenticatedAiAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads/': {
      id: '/api/public/leads/'
      path: '/api/public/leads'
      fullPath: '/api/public/leads/'
      preLoaderRoute: typeof ApiPublicLeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/conversations/': {
      id: '/api/public/conversations/'
      path: '/api/public/conversations'
      fullPath: '/api/public/conversations/'
      preLoaderRoute: typeof ApiPublicConversationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contacts/': {
      id: '/api/public/contacts/'
      path: '/api/public/contacts'
      fullPath: '/api/public/contacts/'
      preLoaderRoute: typeof ApiPublicContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/upsert-conversation': {
      id: '/api/public/webhooks/upsert-conversation'
      path: '/api/public/webhooks/upsert-conversation'
      fullPath: '/api/public/webhooks/upsert-conversation'
      preLoaderRoute: typeof ApiPublicWebhooksUpsertConversationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/update-task': {
      id: '/api/public/webhooks/update-task'
      path: '/api/public/webhooks/update-task'
      fullPath: '/api/public/webhooks/update-task'
      preLoaderRoute: typeof ApiPublicWebhooksUpdateTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/update-lead': {
      id: '/api/public/webhooks/update-lead'
      path: '/api/public/webhooks/update-lead'
      fullPath: '/api/public/webhooks/update-lead'
      preLoaderRoute: typeof ApiPublicWebhooksUpdateLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/update-contact': {
      id: '/api/public/webhooks/update-contact'
      path: '/api/public/webhooks/update-contact'
      fullPath: '/api/public/webhooks/update-contact'
      preLoaderRoute: typeof ApiPublicWebhooksUpdateContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/new-task': {
      id: '/api/public/webhooks/new-task'
      path: '/api/public/webhooks/new-task'
      fullPath: '/api/public/webhooks/new-task'
      preLoaderRoute: typeof ApiPublicWebhooksNewTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/new-message': {
      id: '/api/public/webhooks/new-message'
      path: '/api/public/webhooks/new-message'
      fullPath: '/api/public/webhooks/new-message'
      preLoaderRoute: typeof ApiPublicWebhooksNewMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/new-lead': {
      id: '/api/public/webhooks/new-lead'
      path: '/api/public/webhooks/new-lead'
      fullPath: '/api/public/webhooks/new-lead'
      preLoaderRoute: typeof ApiPublicWebhooksNewLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/new-contact': {
      id: '/api/public/webhooks/new-contact'
      path: '/api/public/webhooks/new-contact'
      fullPath: '/api/public/webhooks/new-contact'
      preLoaderRoute: typeof ApiPublicWebhooksNewContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/channel-status': {
      id: '/api/public/webhooks/channel-status'
      path: '/api/public/webhooks/channel-status'
      fullPath: '/api/public/webhooks/channel-status'
      preLoaderRoute: typeof ApiPublicWebhooksChannelStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/ai-analysis': {
      id: '/api/public/webhooks/ai-analysis'
      path: '/api/public/webhooks/ai-analysis'
      fullPath: '/api/public/webhooks/ai-analysis'
      preLoaderRoute: typeof ApiPublicWebhooksAiAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads/$id/status': {
      id: '/api/public/leads/$id/status'
      path: '/api/public/leads/$id/status'
      fullPath: '/api/public/leads/$id/status'
      preLoaderRoute: typeof ApiPublicLeadsIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads/$id/note': {
      id: '/api/public/leads/$id/note'
      path: '/api/public/leads/$id/note'
      fullPath: '/api/public/leads/$id/note'
      preLoaderRoute: typeof ApiPublicLeadsIdNoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/conversations/$id/messages': {
      id: '/api/public/conversations/$id/messages'
      path: '/api/public/conversations/$id/messages'
      fullPath: '/api/public/conversations/$id/messages'
      preLoaderRoute: typeof ApiPublicConversationsIdMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiAssistantRoute: typeof AuthenticatedAiAssistantRoute
  AuthenticatedAutomationsRoute: typeof AuthenticatedAutomationsRoute
  AuthenticatedChannelsRoute: typeof AuthenticatedChannelsRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedConversationsRoute: typeof AuthenticatedConversationsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedPrioritiesRoute: typeof AuthenticatedPrioritiesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedQueueRoute: typeof AuthenticatedQueueRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedTeamsRoute: typeof AuthenticatedTeamsRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiAssistantRoute: AuthenticatedAiAssistantRoute,
  AuthenticatedAutomationsRoute: AuthenticatedAutomationsRoute,
  AuthenticatedChannelsRoute: AuthenticatedChannelsRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedConversationsRoute: AuthenticatedConversationsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedPrioritiesRoute: AuthenticatedPrioritiesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedQueueRoute: AuthenticatedQueueRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedTeamsRoute: AuthenticatedTeamsRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  ApiPublicWebhooksAiAnalysisRoute: ApiPublicWebhooksAiAnalysisRoute,
  ApiPublicWebhooksChannelStatusRoute: ApiPublicWebhooksChannelStatusRoute,
  ApiPublicWebhooksNewContactRoute: ApiPublicWebhooksNewContactRoute,
  ApiPublicWebhooksNewLeadRoute: ApiPublicWebhooksNewLeadRoute,
  ApiPublicWebhooksNewMessageRoute: ApiPublicWebhooksNewMessageRoute,
  ApiPublicWebhooksNewTaskRoute: ApiPublicWebhooksNewTaskRoute,
  ApiPublicWebhooksUpdateContactRoute: ApiPublicWebhooksUpdateContactRoute,
  ApiPublicWebhooksUpdateLeadRoute: ApiPublicWebhooksUpdateLeadRoute,
  ApiPublicWebhooksUpdateTaskRoute: ApiPublicWebhooksUpdateTaskRoute,
  ApiPublicWebhooksUpsertConversationRoute:
    ApiPublicWebhooksUpsertConversationRoute,
  ApiPublicContactsIndexRoute: ApiPublicContactsIndexRoute,
  ApiPublicConversationsIndexRoute: ApiPublicConversationsIndexRoute,
  ApiPublicLeadsIndexRoute: ApiPublicLeadsIndexRoute,
  ApiPublicConversationsIdMessagesRoute: ApiPublicConversationsIdMessagesRoute,
  ApiPublicLeadsIdNoteRoute: ApiPublicLeadsIdNoteRoute,
  ApiPublicLeadsIdStatusRoute: ApiPublicLeadsIdStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
